# Generated by Django 4.2.7 on 2025-06-21 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('us', 'United States'), ('ca', 'Canada'), ('au', 'Australia'), ('de', 'Germany'), ('fr', 'France'), ('it', 'Italy'), ('es', 'Spain'), ('in', 'India'), ('cn', 'China'), ('jp', 'Japan'), ('br', 'Brazil'), ('other', 'Other')], max_length=10)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('visa_type', models.CharField(blank=True, choices=[('tourist', 'Tourist Visa'), ('work', 'Work Visa'), ('student', 'Student Visa'), ('family', 'Family Visa'), ('business', 'Business Visa'), ('transit', 'Transit Visa')], max_length=20)),
                ('purpose_of_visit', models.TextField(blank=True)),
                ('intended_duration', models.CharField(blank=True, max_length=100)),
                ('previous_uk_visits', models.BooleanField(blank=True, null=True)),
                ('current_occupation', models.CharField(blank=True, max_length=200)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('annual_income', models.CharField(blank=True, max_length=100)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visa_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultation'), ('document_review', 'Document Review'), ('application_submission', 'Application Submission'), ('interview_prep', 'Interview Preparation')], max_length=50)),
                ('scheduled_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
