# Generated by Django 4.2.7 on 2025-06-21 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultation'), ('document_review', 'Document Review'), ('application_submission', 'Application Submission'), ('interview_prep', 'Interview Preparation')], max_length=50)),
                ('scheduled_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('document_processed', 'Document Processed'), ('document_validation', 'Document Validation'), ('text_extraction', 'Text Extraction'), ('processing_error', 'Processing Error')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('file_size_kb', models.IntegerField(blank=True, null=True)),
                ('text_length', models.IntegerField(blank=True, null=True)),
                ('validation_result', models.CharField(blank=True, choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('error', 'Error')], max_length=10)),
                ('processing_successful', models.BooleanField(default=False)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
