# Generated by Django 4.2.7 on 2025-06-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_occupation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='employer_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='intended_duration',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='previous_uk_visits',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_completed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='purpose_of_visit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='visa_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='context_sufficient',
            field=models.BooleanField(default=False, help_text='LLM assessment of whether context is sufficient'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='conversation_insights',
            field=models.TextField(blank=True, help_text='Insights gathered during conversation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_location',
            field=models.CharField(blank=True, help_text='Where user currently lives', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_context_assessment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='missing_context',
            field=models.JSONField(blank=True, default=list, help_text='List of context areas LLM thinks are needed'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_context',
            field=models.TextField(blank=True, help_text="Rich context about user's situation"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='Key-value pairs extracted from conversation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visa_intent',
            field=models.TextField(blank=True, help_text='What user wants to do (travel, work, study, etc.)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(blank=True, help_text="User's nationality/citizenship", max_length=100),
        ),
    ]
