# Generated by Django 4.2.7 on 2025-06-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0002_remove_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='destination_country',
            field=models.CharField(blank=True, help_text='Country user wants to visit/move to', max_length=100),
        ),
    ]
