# Generated by Django 4.2.7 on 2025-06-21 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visa', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reminder_type', models.CharField(choices=[('visa_appointment', 'Visa Appointment'), ('visa_expiry', 'Visa Expiry'), ('document_deadline', 'Document Deadline'), ('consultation', 'Consultation'), ('document_review', 'Document Review'), ('application_submission', 'Application Submission'), ('interview_prep', 'Interview Preparation')], max_length=50)),
                ('target_date', models.DateTimeField(help_text='The date/time this reminder is for')),
                ('reminder_date', models.DateTimeField(help_text='When to send the reminder')),
                ('status', models.CharField(choices=[('active', 'Active'), ('sent', 'Reminder Sent'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reminder_date', 'priority'],
                'indexes': [models.Index(fields=['user', 'status', 'reminder_date'], name='visa_remind_user_id_54fa43_idx'), models.Index(fields=['reminder_date', 'email_sent'], name='visa_remind_reminde_20820e_idx')],
            },
        ),
    ]
